### ISSUE TITLE
Support simple JDK version string

### ISSUE THREAD

**Issue by mosabua** [takari/jdkget#16]
It feels like a bit of a pain having to know what exact version string to use. Can we make it work for just "1.8" and have it default to the latest known version of 1.8.x at the time of invocation?

**Comment by mosabua** [comment]
Fyi  @atanasenko this would make it more user friendly in looper.yml files imho

**Comment by atanasenko** [comment]
It's actually already supported since we're using our own list of versions @ https://github.com/takari/jdkget/blob/master/jdkreleases.xml

**Comment by mosabua** [comment]
Hm... I get 

9 Checking out Revision c9813a7a1be33759617ca45f484a5406a1c5e101 (origin/master)
11:39:49 FATAL: 1
11:39:49 java.lang.ArrayIndexOutOfBoundsException: 1
11:39:49    at io.takari.jdkget.JdkGetter$JdkVersion.parse(JdkGetter.java:272)
11:39:49    at io.takari.looper.job.provisioner.tools.jdk.JDKToolDefinition.normalize(JDKToolDefinition.java:68)
11:39:49    at io.takari.looper.job.provisioner.tools.jdk.JDKToolDefinition.createTool(JDKToolDefinition.java:56)
11:39:49    at io.takari.looper.job.provisioner.tools.jdk.JDKToolDefinition.createTool(JDKToolDefinition.java:1)
11:39:49    at io.takari.looper.job.provisioner.ToolDefinition.getInstallation(ToolDefinition.java:55)
11:39:49    at io.takari.looper.job.config.impl.ToolSelector.addTool(ToolSelector.java:47)
11:39:49    at io.takari.looper.job.config.impl.ToolSelector.configure(ToolSelector.java:33)
11:39:49    at io.takari.looper.job.LooperBuild$Exec.doRun(LooperBuild.java:858)
11:39:49    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
11:39:49    at hudson.model.Run.execute(Run.java:1720)
11:39:49    at io.takari.looper.job.LooperBuild.run(LooperBuild.java:587)
11:39:49    at hudson.model.ResourceController.execute(ResourceController.java:98)
11:39:49    at hudson.model.Executor.run(Executor.java:404)

When using it with 1.8 in https://github.com/simpligility/ksoap2-android

**Comment by mosabua** [comment]
Just "8" seems to work though.

**Comment by mosabua** [comment]
8u92 works as well.

**Comment by mosabua** [comment]
Fixed by https://github.com/takari/jdkget/commit/5a3bc69de01fcfb0047b9a519876bbd0580d273a
